import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:goal_tracker/features/scheduled_tasks/presentation/widgets/scheduled_task_card.dart';
import 'package:goal_tracker/data/models/scheduled_task.dart';

void main() {
  // Helper to create a test scheduled task
  ScheduledTask createTestTask({
    int id = 1,
    String title = 'Test Task',
    int goalId = 1,
    int hour = 9,
    int minute = 0,
    int duration = 60,
    String colorHex = '#FF5733',
    String schedulingMethod = 'rule-based',
    double? mlConfidence,
    bool isCompleted = false,
  }) {
    final now = DateTime.now();
    final task = ScheduledTask()
      ..id = id
      ..goalId = goalId
      ..title = title
      ..scheduledDate = DateTime(now.year, now.month, now.day)
      ..scheduledStartTime = DateTime(now.year, now.month, now.day, hour, minute)
      ..originalScheduledTime = DateTime(now.year, now.month, now.day, hour, minute)
      ..duration = duration
      ..colorHex = colorHex
      ..iconName = 'fitness_center'
      ..schedulingMethod = schedulingMethod
      ..mlConfidence = mlConfidence
      ..isCompleted = isCompleted
      ..wasRescheduled = false
      ..rescheduleCount = 0
      ..isAutoGenerated = true
      ..createdAt = DateTime.now();

    return task;
  }

  // Helper to create a simple test widget (without database dependencies)
  Widget createSimpleTestWidget({
    required ScheduledTask task,
    VoidCallback? onCompleted,
  }) {
    return ProviderScope(
      child: MaterialApp(
        theme: ThemeData.dark(),
        home: Scaffold(
          body: ScheduledTaskCard(
            task: task,
            onCompleted: onCompleted,
          ),
        ),
      ),
    );
  }

  group('ScheduledTaskCard', () {
    testWidgets('displays task title', (tester) async {
      final task = createTestTask(title: 'Study Flutter');

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.text('Study Flutter'), findsOneWidget);
    });

    testWidgets('displays scheduled time', (tester) async {
      final task = createTestTask(hour: 14, minute: 30);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.text('14:30'), findsOneWidget);
    });

    testWidgets('displays duration', (tester) async {
      final task = createTestTask(duration: 45);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.text('45min'), findsOneWidget);
    });

    testWidgets('displays ML badge for ml-based scheduling', (tester) async {
      final task = createTestTask(
        schedulingMethod: 'ml-based',
        mlConfidence: 0.85,
      );

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.text('ML'), findsOneWidget);
      expect(find.byIcon(Icons.psychology), findsOneWidget);
    });

    testWidgets('does not display ML badge for rule-based scheduling',
        (tester) async {
      final task = createTestTask(schedulingMethod: 'rule-based');

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.text('ML'), findsNothing);
    });

    testWidgets('displays checkbox', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.byType(Checkbox), findsOneWidget);
    });

    testWidgets('checkbox is unchecked for incomplete task', (tester) async {
      final task = createTestTask(isCompleted: false);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      final checkbox = tester.widget<Checkbox>(find.byType(Checkbox));
      expect(checkbox.value, false);
    });

    testWidgets('checkbox is checked for completed task', (tester) async {
      final task = createTestTask(isCompleted: true);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      final checkbox = tester.widget<Checkbox>(find.byType(Checkbox));
      expect(checkbox.value, true);
    });

    testWidgets('completed task has strikethrough text', (tester) async {
      final task = createTestTask(title: 'Completed Task', isCompleted: true);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      final textWidget = tester.widget<Text>(find.text('Completed Task'));
      expect(
        textWidget.style?.decoration,
        TextDecoration.lineThrough,
      );
    });

    testWidgets('incomplete task does not have strikethrough', (tester) async {
      final task = createTestTask(title: 'Pending Task', isCompleted: false);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      final textWidget = tester.widget<Text>(find.text('Pending Task'));
      expect(
        textWidget.style?.decoration,
        isNot(TextDecoration.lineThrough),
      );
    });

    testWidgets('displays color indicator', (tester) async {
      final task = createTestTask(colorHex: '#00FF00');

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      // Find the color indicator container (width: 4, height: 48)
      final containers = find.byType(Container);
      expect(containers, findsWidgets);
    });

    testWidgets('displays time icon', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.byIcon(Icons.access_time), findsOneWidget);
    });

    testWidgets('displays timer icon for duration', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.byIcon(Icons.timer), findsOneWidget);
    });

    testWidgets('card is tappable when not completed', (tester) async {
      final task = createTestTask(isCompleted: false);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      final inkWell = find.byType(InkWell);
      expect(inkWell, findsOneWidget);
    });

    testWidgets('checkbox is disabled when task is completed', (tester) async {
      final task = createTestTask(isCompleted: true);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      final checkbox = tester.widget<Checkbox>(find.byType(Checkbox));
      expect(checkbox.onChanged, isNull);
    });

    testWidgets('handles task with null color gracefully', (tester) async {
      final now = DateTime.now();
      final task = ScheduledTask()
        ..id = 1
        ..goalId = 1
        ..title = 'No Color Task'
        ..scheduledDate = DateTime(now.year, now.month, now.day)
        ..scheduledStartTime = DateTime(now.year, now.month, now.day, 9)
        ..originalScheduledTime = DateTime(now.year, now.month, now.day, 9)
        ..duration = 60
        ..colorHex = null // No color
        ..schedulingMethod = 'rule-based'
        ..isCompleted = false
        ..wasRescheduled = false
        ..rescheduleCount = 0
        ..isAutoGenerated = true
        ..createdAt = DateTime.now();

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      // Should not throw, should use default color
      expect(find.text('No Color Task'), findsOneWidget);
    });

    testWidgets('displays morning time correctly', (tester) async {
      final task = createTestTask(hour: 6, minute: 0);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.text('06:00'), findsOneWidget);
    });

    testWidgets('displays evening time correctly', (tester) async {
      final task = createTestTask(hour: 21, minute: 45);

      await tester.pumpWidget(createSimpleTestWidget(task: task));

      expect(find.text('21:45'), findsOneWidget);
    });

    testWidgets('different colors for completed vs incomplete tasks',
        (tester) async {
      final incompleteTask = createTestTask(
        title: 'Incomplete',
        isCompleted: false,
        colorHex: '#FF0000',
      );

      await tester.pumpWidget(createSimpleTestWidget(task: incompleteTask));

      // Just verify it renders without checking specific colors
      expect(find.text('Incomplete'), findsOneWidget);
    });
  });
}
