import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:goal_tracker/features/scheduled_tasks/presentation/widgets/task_completion_modal.dart';
import 'package:goal_tracker/data/models/scheduled_task.dart';

void main() {
  // Helper to create a test scheduled task
  ScheduledTask createTestTask({
    int id = 1,
    String title = 'Test Task',
    int goalId = 1,
    int hour = 9,
    int duration = 60,
    String colorHex = '#FF5733',
  }) {
    final now = DateTime.now();
    final task = ScheduledTask()
      ..id = id
      ..goalId = goalId
      ..title = title
      ..scheduledDate = DateTime(now.year, now.month, now.day)
      ..scheduledStartTime = DateTime(now.year, now.month, now.day, hour)
      ..originalScheduledTime = DateTime(now.year, now.month, now.day, hour)
      ..duration = duration
      ..colorHex = colorHex
      ..iconName = 'fitness_center'
      ..schedulingMethod = 'rule-based'
      ..isCompleted = false
      ..wasRescheduled = false
      ..rescheduleCount = 0
      ..isAutoGenerated = true
      ..createdAt = DateTime.now();

    return task;
  }

  // Helper to wrap widget with necessary providers
  Widget createTestWidget({
    required ScheduledTask task,
    required Function(
      DateTime actualStartTime,
      int actualDurationMinutes,
      double productivityRating,
      String? notes,
    ) onComplete,
  }) {
    return ProviderScope(
      child: MaterialApp(
        theme: ThemeData.dark(),
        home: Scaffold(
          body: Builder(
            builder: (context) => ElevatedButton(
              onPressed: () {
                showModalBottomSheet(
                  context: context,
                  isScrollControlled: true,
                  backgroundColor: Colors.transparent,
                  builder: (context) => TaskCompletionModal(
                    task: task,
                    onComplete: onComplete,
                  ),
                );
              },
              child: const Text('Show Modal'),
            ),
          ),
        ),
      ),
    );
  }

  group('TaskCompletionModal', () {
    testWidgets('displays task title', (tester) async {
      final task = createTestTask(title: 'My Task Title');

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      // Open modal
      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      expect(find.text('My Task Title'), findsOneWidget);
    });

    testWidgets('displays productivity rating question', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      expect(find.text('How productive were you?'), findsOneWidget);
    });

    testWidgets('displays 5 star rating buttons', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // Should have star icons for rating
      expect(find.byIcon(Icons.star), findsWidgets);
      expect(find.byIcon(Icons.star_border), findsWidgets);
    });

    testWidgets('displays start time picker section', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      expect(find.text('When did you actually start?'), findsOneWidget);
    });

    testWidgets('displays duration picker section', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      expect(find.text('How long did it take?'), findsOneWidget);
    });

    testWidgets('displays notes section', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      expect(find.text('Notes (optional)'), findsOneWidget);
      expect(find.byType(TextField), findsOneWidget);
    });

    testWidgets('displays complete button', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      expect(find.text('Complete Task'), findsOneWidget);
    });

    testWidgets('displays close button', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      expect(find.byIcon(Icons.close), findsOneWidget);
    });

    testWidgets('selecting star updates rating', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // Default rating is 3, so we should see "Moderately productive"
      expect(find.text('Moderately productive'), findsOneWidget);

      // Find star icons (both filled and outline)
      final starFinder = find.byIcon(Icons.star_border);
      
      // Tap on the first star_border (which would be rating 4 or 5)
      if (starFinder.evaluate().isNotEmpty) {
        await tester.tap(starFinder.first);
        await tester.pumpAndSettle();
      }
    });

    testWidgets('duration can be decreased', (tester) async {
      final task = createTestTask(duration: 60);

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // Initial duration display
      expect(find.text('1h 0m'), findsOneWidget);

      // Find decrease button
      final decreaseButton = find.byIcon(Icons.remove_circle_outline);
      expect(decreaseButton, findsOneWidget);

      await tester.tap(decreaseButton);
      await tester.pumpAndSettle();

      // Duration should now be 55 minutes
      expect(find.text('55m'), findsOneWidget);
    });

    testWidgets('duration can be increased', (tester) async {
      final task = createTestTask(duration: 60);

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // Find increase button
      final increaseButton = find.byIcon(Icons.add_circle_outline);
      expect(increaseButton, findsOneWidget);

      await tester.tap(increaseButton);
      await tester.pumpAndSettle();

      // Duration should now be 65 minutes
      expect(find.text('1h 5m'), findsOneWidget);
    });

    testWidgets('calls onComplete with correct values when submitted',
        (tester) async {
      final task = createTestTask(duration: 30);

      DateTime? actualStartTime;
      int? actualDuration;
      double? productivityRating;
      String? notes;

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (start, duration, rating, noteText) {
          actualStartTime = start;
          actualDuration = duration;
          productivityRating = rating;
          notes = noteText;
        },
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // Enter notes
      await tester.enterText(find.byType(TextField), 'Great session!');
      await tester.pumpAndSettle();

      // Scroll to and tap submit button
      await tester.ensureVisible(find.text('Complete Task'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Complete Task'));
      await tester.pumpAndSettle();

      // Verify callback was called with values
      expect(actualStartTime, isNotNull);
      expect(actualDuration, 30); // Default duration
      expect(productivityRating, 3.0); // Default rating
      expect(notes, 'Great session!');
    });

    testWidgets('closes modal on close button tap', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // Modal should be visible
      expect(find.text('How productive were you?'), findsOneWidget);

      // Tap close button
      await tester.tap(find.byIcon(Icons.close));
      await tester.pumpAndSettle();

      // Modal should be closed
      expect(find.text('How productive were you?'), findsNothing);
    });

    testWidgets('closes modal after submission', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // Modal should be visible
      expect(find.text('Complete Task'), findsOneWidget);

      // Scroll to make the button visible and tap it
      await tester.ensureVisible(find.text('Complete Task'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Complete Task'));
      await tester.pumpAndSettle();

      // Modal should be closed
      expect(find.text('Complete Task'), findsNothing);
    });

    testWidgets('displays task color indicator', (tester) async {
      final task = createTestTask(colorHex: '#00FF00');

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // There should be a colored container (color indicator)
      final containers = find.byType(Container);
      expect(containers, findsWidgets);
    });

    testWidgets('displays rating labels correctly', (tester) async {
      final task = createTestTask();

      await tester.pumpWidget(createTestWidget(
        task: task,
        onComplete: (_, __, ___, ____) {},
      ));

      await tester.tap(find.text('Show Modal'));
      await tester.pumpAndSettle();

      // Default rating is 3
      expect(find.text('Moderately productive'), findsOneWidget);
    });
  });
}
