import 'package:isar/isar.dart';

part 'scheduled_task.g.dart';

@collection
class ScheduledTask {
  Id id = Isar.autoIncrement;

  // Link to the goal this was generated from
  late int goalId;

  // Scheduling info
  @Index()
  late DateTime scheduledDate; // Just the date (normalized)
  late DateTime scheduledStartTime; // Full datetime with time
  late int duration; // In minutes

  // Task details (copied from goal)
  late String title;
  String? colorHex;
  String? iconName;

  // Completion tracking
  @Index()
  late bool isCompleted;
  DateTime? completedAt;

  // === ML TRACKING DATA ===
  // What was originally scheduled
  late DateTime originalScheduledTime; // What the scheduler initially chose
  late String schedulingMethod; // 'rule-based' or 'ml-based'
  double? mlConfidence; // If ML was used, confidence score (0.0-1.0)

  // What actually happened (for ML training)
  DateTime? actualStartTime; // When user actually started the task
  int? actualDuration; // How long it actually took (minutes)
  int? productivityRating; // User's rating: 1-5 stars
  String? completionNotes; // User's notes about the session

  // User behavior signals (important for ML)
  late bool wasRescheduled; // Did user move this task?
  DateTime? rescheduledTo; // If yes, when did they move it to?
  late int rescheduleCount; // How many times was this task moved?

  // Milestone tracking
  int? milestoneId; // Which milestone this task is working towards
  bool? milestoneCompleted; // Was the milestone completed in this session?

  // Metadata
  late DateTime createdAt;
  late bool isAutoGenerated; // true if created by scheduler, false if manual

  // Reason why task was scheduled at this time (for UI display)
  // This is null for manually created tasks or after reschedule
  String? schedulingReason;

  // Constructor
  ScheduledTask() {
    isCompleted = false;
    wasRescheduled = false;
    rescheduleCount = 0;
    isAutoGenerated = true;
    createdAt = DateTime.now();
    schedulingMethod = 'rule-based';
  }
}
