// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'scheduled_task.dart';

// **************************************************************************
// IsarCollectionGenerator
// **************************************************************************

// coverage:ignore-file
// ignore_for_file: duplicate_ignore, non_constant_identifier_names, constant_identifier_names, invalid_use_of_protected_member, unnecessary_cast, prefer_const_constructors, lines_longer_than_80_chars, require_trailing_commas, inference_failure_on_function_invocation, unnecessary_parenthesis, unnecessary_raw_strings, unnecessary_null_checks, join_return_with_assignment, prefer_final_locals, avoid_js_rounded_ints, avoid_positional_boolean_parameters, always_specify_types

extension GetScheduledTaskCollection on Isar {
  IsarCollection<ScheduledTask> get scheduledTasks => this.collection();
}

const ScheduledTaskSchema = CollectionSchema(
  name: r'ScheduledTask',
  id: -2920409038306608989,
  properties: {
    r'actualDuration': PropertySchema(
      id: 0,
      name: r'actualDuration',
      type: IsarType.long,
    ),
    r'actualStartTime': PropertySchema(
      id: 1,
      name: r'actualStartTime',
      type: IsarType.dateTime,
    ),
    r'colorHex': PropertySchema(
      id: 2,
      name: r'colorHex',
      type: IsarType.string,
    ),
    r'completedAt': PropertySchema(
      id: 3,
      name: r'completedAt',
      type: IsarType.dateTime,
    ),
    r'completionNotes': PropertySchema(
      id: 4,
      name: r'completionNotes',
      type: IsarType.string,
    ),
    r'createdAt': PropertySchema(
      id: 5,
      name: r'createdAt',
      type: IsarType.dateTime,
    ),
    r'duration': PropertySchema(
      id: 6,
      name: r'duration',
      type: IsarType.long,
    ),
    r'goalId': PropertySchema(
      id: 7,
      name: r'goalId',
      type: IsarType.long,
    ),
    r'iconName': PropertySchema(
      id: 8,
      name: r'iconName',
      type: IsarType.string,
    ),
    r'isAutoGenerated': PropertySchema(
      id: 9,
      name: r'isAutoGenerated',
      type: IsarType.bool,
    ),
    r'isCompleted': PropertySchema(
      id: 10,
      name: r'isCompleted',
      type: IsarType.bool,
    ),
    r'milestoneCompleted': PropertySchema(
      id: 11,
      name: r'milestoneCompleted',
      type: IsarType.bool,
    ),
    r'milestoneId': PropertySchema(
      id: 12,
      name: r'milestoneId',
      type: IsarType.long,
    ),
    r'mlConfidence': PropertySchema(
      id: 13,
      name: r'mlConfidence',
      type: IsarType.double,
    ),
    r'originalScheduledTime': PropertySchema(
      id: 14,
      name: r'originalScheduledTime',
      type: IsarType.dateTime,
    ),
    r'productivityRating': PropertySchema(
      id: 15,
      name: r'productivityRating',
      type: IsarType.long,
    ),
    r'rescheduleCount': PropertySchema(
      id: 16,
      name: r'rescheduleCount',
      type: IsarType.long,
    ),
    r'rescheduledTo': PropertySchema(
      id: 17,
      name: r'rescheduledTo',
      type: IsarType.dateTime,
    ),
    r'scheduledDate': PropertySchema(
      id: 18,
      name: r'scheduledDate',
      type: IsarType.dateTime,
    ),
    r'scheduledStartTime': PropertySchema(
      id: 19,
      name: r'scheduledStartTime',
      type: IsarType.dateTime,
    ),
    r'schedulingMethod': PropertySchema(
      id: 20,
      name: r'schedulingMethod',
      type: IsarType.string,
    ),
    r'title': PropertySchema(
      id: 21,
      name: r'title',
      type: IsarType.string,
    ),
    r'wasRescheduled': PropertySchema(
      id: 22,
      name: r'wasRescheduled',
      type: IsarType.bool,
    )
  },
  estimateSize: _scheduledTaskEstimateSize,
  serialize: _scheduledTaskSerialize,
  deserialize: _scheduledTaskDeserialize,
  deserializeProp: _scheduledTaskDeserializeProp,
  idName: r'id',
  indexes: {
    r'scheduledDate': IndexSchema(
      id: -6773496565145745994,
      name: r'scheduledDate',
      unique: false,
      replace: false,
      properties: [
        IndexPropertySchema(
          name: r'scheduledDate',
          type: IndexType.value,
          caseSensitive: false,
        )
      ],
    ),
    r'isCompleted': IndexSchema(
      id: -7936144632215868537,
      name: r'isCompleted',
      unique: false,
      replace: false,
      properties: [
        IndexPropertySchema(
          name: r'isCompleted',
          type: IndexType.value,
          caseSensitive: false,
        )
      ],
    )
  },
  links: {},
  embeddedSchemas: {},
  getId: _scheduledTaskGetId,
  getLinks: _scheduledTaskGetLinks,
  attach: _scheduledTaskAttach,
  version: '3.1.0+1',
);

int _scheduledTaskEstimateSize(
  ScheduledTask object,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  var bytesCount = offsets.last;
  {
    final value = object.colorHex;
    if (value != null) {
      bytesCount += 3 + value.length * 3;
    }
  }
  {
    final value = object.completionNotes;
    if (value != null) {
      bytesCount += 3 + value.length * 3;
    }
  }
  {
    final value = object.iconName;
    if (value != null) {
      bytesCount += 3 + value.length * 3;
    }
  }
  bytesCount += 3 + object.schedulingMethod.length * 3;
  bytesCount += 3 + object.title.length * 3;
  return bytesCount;
}

void _scheduledTaskSerialize(
  ScheduledTask object,
  IsarWriter writer,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  writer.writeLong(offsets[0], object.actualDuration);
  writer.writeDateTime(offsets[1], object.actualStartTime);
  writer.writeString(offsets[2], object.colorHex);
  writer.writeDateTime(offsets[3], object.completedAt);
  writer.writeString(offsets[4], object.completionNotes);
  writer.writeDateTime(offsets[5], object.createdAt);
  writer.writeLong(offsets[6], object.duration);
  writer.writeLong(offsets[7], object.goalId);
  writer.writeString(offsets[8], object.iconName);
  writer.writeBool(offsets[9], object.isAutoGenerated);
  writer.writeBool(offsets[10], object.isCompleted);
  writer.writeBool(offsets[11], object.milestoneCompleted);
  writer.writeLong(offsets[12], object.milestoneId);
  writer.writeDouble(offsets[13], object.mlConfidence);
  writer.writeDateTime(offsets[14], object.originalScheduledTime);
  writer.writeLong(offsets[15], object.productivityRating);
  writer.writeLong(offsets[16], object.rescheduleCount);
  writer.writeDateTime(offsets[17], object.rescheduledTo);
  writer.writeDateTime(offsets[18], object.scheduledDate);
  writer.writeDateTime(offsets[19], object.scheduledStartTime);
  writer.writeString(offsets[20], object.schedulingMethod);
  writer.writeString(offsets[21], object.title);
  writer.writeBool(offsets[22], object.wasRescheduled);
}

ScheduledTask _scheduledTaskDeserialize(
  Id id,
  IsarReader reader,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  final object = ScheduledTask();
  object.actualDuration = reader.readLongOrNull(offsets[0]);
  object.actualStartTime = reader.readDateTimeOrNull(offsets[1]);
  object.colorHex = reader.readStringOrNull(offsets[2]);
  object.completedAt = reader.readDateTimeOrNull(offsets[3]);
  object.completionNotes = reader.readStringOrNull(offsets[4]);
  object.createdAt = reader.readDateTime(offsets[5]);
  object.duration = reader.readLong(offsets[6]);
  object.goalId = reader.readLong(offsets[7]);
  object.iconName = reader.readStringOrNull(offsets[8]);
  object.id = id;
  object.isAutoGenerated = reader.readBool(offsets[9]);
  object.isCompleted = reader.readBool(offsets[10]);
  object.milestoneCompleted = reader.readBoolOrNull(offsets[11]);
  object.milestoneId = reader.readLongOrNull(offsets[12]);
  object.mlConfidence = reader.readDoubleOrNull(offsets[13]);
  object.originalScheduledTime = reader.readDateTime(offsets[14]);
  object.productivityRating = reader.readLongOrNull(offsets[15]);
  object.rescheduleCount = reader.readLong(offsets[16]);
  object.rescheduledTo = reader.readDateTimeOrNull(offsets[17]);
  object.scheduledDate = reader.readDateTime(offsets[18]);
  object.scheduledStartTime = reader.readDateTime(offsets[19]);
  object.schedulingMethod = reader.readString(offsets[20]);
  object.title = reader.readString(offsets[21]);
  object.wasRescheduled = reader.readBool(offsets[22]);
  return object;
}

P _scheduledTaskDeserializeProp<P>(
  IsarReader reader,
  int propertyId,
  int offset,
  Map<Type, List<int>> allOffsets,
) {
  switch (propertyId) {
    case 0:
      return (reader.readLongOrNull(offset)) as P;
    case 1:
      return (reader.readDateTimeOrNull(offset)) as P;
    case 2:
      return (reader.readStringOrNull(offset)) as P;
    case 3:
      return (reader.readDateTimeOrNull(offset)) as P;
    case 4:
      return (reader.readStringOrNull(offset)) as P;
    case 5:
      return (reader.readDateTime(offset)) as P;
    case 6:
      return (reader.readLong(offset)) as P;
    case 7:
      return (reader.readLong(offset)) as P;
    case 8:
      return (reader.readStringOrNull(offset)) as P;
    case 9:
      return (reader.readBool(offset)) as P;
    case 10:
      return (reader.readBool(offset)) as P;
    case 11:
      return (reader.readBoolOrNull(offset)) as P;
    case 12:
      return (reader.readLongOrNull(offset)) as P;
    case 13:
      return (reader.readDoubleOrNull(offset)) as P;
    case 14:
      return (reader.readDateTime(offset)) as P;
    case 15:
      return (reader.readLongOrNull(offset)) as P;
    case 16:
      return (reader.readLong(offset)) as P;
    case 17:
      return (reader.readDateTimeOrNull(offset)) as P;
    case 18:
      return (reader.readDateTime(offset)) as P;
    case 19:
      return (reader.readDateTime(offset)) as P;
    case 20:
      return (reader.readString(offset)) as P;
    case 21:
      return (reader.readString(offset)) as P;
    case 22:
      return (reader.readBool(offset)) as P;
    default:
      throw IsarError('Unknown property with id $propertyId');
  }
}

Id _scheduledTaskGetId(ScheduledTask object) {
  return object.id;
}

List<IsarLinkBase<dynamic>> _scheduledTaskGetLinks(ScheduledTask object) {
  return [];
}

void _scheduledTaskAttach(
    IsarCollection<dynamic> col, Id id, ScheduledTask object) {
  object.id = id;
}

extension ScheduledTaskQueryWhereSort
    on QueryBuilder<ScheduledTask, ScheduledTask, QWhere> {
  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhere> anyId() {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(const IdWhereClause.any());
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhere> anyScheduledDate() {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        const IndexWhereClause.any(indexName: r'scheduledDate'),
      );
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhere> anyIsCompleted() {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        const IndexWhereClause.any(indexName: r'isCompleted'),
      );
    });
  }
}

extension ScheduledTaskQueryWhere
    on QueryBuilder<ScheduledTask, ScheduledTask, QWhereClause> {
  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause> idEqualTo(
      Id id) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IdWhereClause.between(
        lower: id,
        upper: id,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause> idNotEqualTo(
      Id id) {
    return QueryBuilder.apply(this, (query) {
      if (query.whereSort == Sort.asc) {
        return query
            .addWhereClause(
              IdWhereClause.lessThan(upper: id, includeUpper: false),
            )
            .addWhereClause(
              IdWhereClause.greaterThan(lower: id, includeLower: false),
            );
      } else {
        return query
            .addWhereClause(
              IdWhereClause.greaterThan(lower: id, includeLower: false),
            )
            .addWhereClause(
              IdWhereClause.lessThan(upper: id, includeUpper: false),
            );
      }
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause> idGreaterThan(
      Id id,
      {bool include = false}) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        IdWhereClause.greaterThan(lower: id, includeLower: include),
      );
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause> idLessThan(
      Id id,
      {bool include = false}) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        IdWhereClause.lessThan(upper: id, includeUpper: include),
      );
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause> idBetween(
    Id lowerId,
    Id upperId, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IdWhereClause.between(
        lower: lowerId,
        includeLower: includeLower,
        upper: upperId,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause>
      scheduledDateEqualTo(DateTime scheduledDate) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IndexWhereClause.equalTo(
        indexName: r'scheduledDate',
        value: [scheduledDate],
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause>
      scheduledDateNotEqualTo(DateTime scheduledDate) {
    return QueryBuilder.apply(this, (query) {
      if (query.whereSort == Sort.asc) {
        return query
            .addWhereClause(IndexWhereClause.between(
              indexName: r'scheduledDate',
              lower: [],
              upper: [scheduledDate],
              includeUpper: false,
            ))
            .addWhereClause(IndexWhereClause.between(
              indexName: r'scheduledDate',
              lower: [scheduledDate],
              includeLower: false,
              upper: [],
            ));
      } else {
        return query
            .addWhereClause(IndexWhereClause.between(
              indexName: r'scheduledDate',
              lower: [scheduledDate],
              includeLower: false,
              upper: [],
            ))
            .addWhereClause(IndexWhereClause.between(
              indexName: r'scheduledDate',
              lower: [],
              upper: [scheduledDate],
              includeUpper: false,
            ));
      }
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause>
      scheduledDateGreaterThan(
    DateTime scheduledDate, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IndexWhereClause.between(
        indexName: r'scheduledDate',
        lower: [scheduledDate],
        includeLower: include,
        upper: [],
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause>
      scheduledDateLessThan(
    DateTime scheduledDate, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IndexWhereClause.between(
        indexName: r'scheduledDate',
        lower: [],
        upper: [scheduledDate],
        includeUpper: include,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause>
      scheduledDateBetween(
    DateTime lowerScheduledDate,
    DateTime upperScheduledDate, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IndexWhereClause.between(
        indexName: r'scheduledDate',
        lower: [lowerScheduledDate],
        includeLower: includeLower,
        upper: [upperScheduledDate],
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause>
      isCompletedEqualTo(bool isCompleted) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IndexWhereClause.equalTo(
        indexName: r'isCompleted',
        value: [isCompleted],
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterWhereClause>
      isCompletedNotEqualTo(bool isCompleted) {
    return QueryBuilder.apply(this, (query) {
      if (query.whereSort == Sort.asc) {
        return query
            .addWhereClause(IndexWhereClause.between(
              indexName: r'isCompleted',
              lower: [],
              upper: [isCompleted],
              includeUpper: false,
            ))
            .addWhereClause(IndexWhereClause.between(
              indexName: r'isCompleted',
              lower: [isCompleted],
              includeLower: false,
              upper: [],
            ));
      } else {
        return query
            .addWhereClause(IndexWhereClause.between(
              indexName: r'isCompleted',
              lower: [isCompleted],
              includeLower: false,
              upper: [],
            ))
            .addWhereClause(IndexWhereClause.between(
              indexName: r'isCompleted',
              lower: [],
              upper: [isCompleted],
              includeUpper: false,
            ));
      }
    });
  }
}

extension ScheduledTaskQueryFilter
    on QueryBuilder<ScheduledTask, ScheduledTask, QFilterCondition> {
  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualDurationIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'actualDuration',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualDurationIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'actualDuration',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualDurationEqualTo(int? value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'actualDuration',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualDurationGreaterThan(
    int? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'actualDuration',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualDurationLessThan(
    int? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'actualDuration',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualDurationBetween(
    int? lower,
    int? upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'actualDuration',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualStartTimeIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'actualStartTime',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualStartTimeIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'actualStartTime',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualStartTimeEqualTo(DateTime? value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'actualStartTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualStartTimeGreaterThan(
    DateTime? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'actualStartTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualStartTimeLessThan(
    DateTime? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'actualStartTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      actualStartTimeBetween(
    DateTime? lower,
    DateTime? upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'actualStartTime',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'colorHex',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'colorHex',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexEqualTo(
    String? value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'colorHex',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexGreaterThan(
    String? value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'colorHex',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexLessThan(
    String? value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'colorHex',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexBetween(
    String? lower,
    String? upper, {
    bool includeLower = true,
    bool includeUpper = true,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'colorHex',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexStartsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.startsWith(
        property: r'colorHex',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexEndsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.endsWith(
        property: r'colorHex',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexContains(String value, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.contains(
        property: r'colorHex',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexMatches(String pattern, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.matches(
        property: r'colorHex',
        wildcard: pattern,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexIsEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'colorHex',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      colorHexIsNotEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        property: r'colorHex',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completedAtIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'completedAt',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completedAtIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'completedAt',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completedAtEqualTo(DateTime? value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'completedAt',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completedAtGreaterThan(
    DateTime? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'completedAt',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completedAtLessThan(
    DateTime? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'completedAt',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completedAtBetween(
    DateTime? lower,
    DateTime? upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'completedAt',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'completionNotes',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'completionNotes',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesEqualTo(
    String? value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'completionNotes',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesGreaterThan(
    String? value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'completionNotes',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesLessThan(
    String? value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'completionNotes',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesBetween(
    String? lower,
    String? upper, {
    bool includeLower = true,
    bool includeUpper = true,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'completionNotes',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesStartsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.startsWith(
        property: r'completionNotes',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesEndsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.endsWith(
        property: r'completionNotes',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesContains(String value, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.contains(
        property: r'completionNotes',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesMatches(String pattern, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.matches(
        property: r'completionNotes',
        wildcard: pattern,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesIsEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'completionNotes',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      completionNotesIsNotEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        property: r'completionNotes',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      createdAtEqualTo(DateTime value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'createdAt',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      createdAtGreaterThan(
    DateTime value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'createdAt',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      createdAtLessThan(
    DateTime value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'createdAt',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      createdAtBetween(
    DateTime lower,
    DateTime upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'createdAt',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      durationEqualTo(int value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'duration',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      durationGreaterThan(
    int value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'duration',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      durationLessThan(
    int value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'duration',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      durationBetween(
    int lower,
    int upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'duration',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      goalIdEqualTo(int value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'goalId',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      goalIdGreaterThan(
    int value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'goalId',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      goalIdLessThan(
    int value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'goalId',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      goalIdBetween(
    int lower,
    int upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'goalId',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'iconName',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'iconName',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameEqualTo(
    String? value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'iconName',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameGreaterThan(
    String? value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'iconName',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameLessThan(
    String? value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'iconName',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameBetween(
    String? lower,
    String? upper, {
    bool includeLower = true,
    bool includeUpper = true,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'iconName',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameStartsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.startsWith(
        property: r'iconName',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameEndsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.endsWith(
        property: r'iconName',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameContains(String value, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.contains(
        property: r'iconName',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameMatches(String pattern, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.matches(
        property: r'iconName',
        wildcard: pattern,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameIsEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'iconName',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      iconNameIsNotEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        property: r'iconName',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition> idEqualTo(
      Id value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'id',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      idGreaterThan(
    Id value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'id',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition> idLessThan(
    Id value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'id',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition> idBetween(
    Id lower,
    Id upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'id',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      isAutoGeneratedEqualTo(bool value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'isAutoGenerated',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      isCompletedEqualTo(bool value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'isCompleted',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneCompletedIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'milestoneCompleted',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneCompletedIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'milestoneCompleted',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneCompletedEqualTo(bool? value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'milestoneCompleted',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneIdIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'milestoneId',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneIdIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'milestoneId',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneIdEqualTo(int? value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'milestoneId',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneIdGreaterThan(
    int? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'milestoneId',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneIdLessThan(
    int? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'milestoneId',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      milestoneIdBetween(
    int? lower,
    int? upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'milestoneId',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      mlConfidenceIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'mlConfidence',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      mlConfidenceIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'mlConfidence',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      mlConfidenceEqualTo(
    double? value, {
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'mlConfidence',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      mlConfidenceGreaterThan(
    double? value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'mlConfidence',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      mlConfidenceLessThan(
    double? value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'mlConfidence',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      mlConfidenceBetween(
    double? lower,
    double? upper, {
    bool includeLower = true,
    bool includeUpper = true,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'mlConfidence',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      originalScheduledTimeEqualTo(DateTime value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'originalScheduledTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      originalScheduledTimeGreaterThan(
    DateTime value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'originalScheduledTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      originalScheduledTimeLessThan(
    DateTime value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'originalScheduledTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      originalScheduledTimeBetween(
    DateTime lower,
    DateTime upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'originalScheduledTime',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      productivityRatingIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'productivityRating',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      productivityRatingIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'productivityRating',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      productivityRatingEqualTo(int? value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'productivityRating',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      productivityRatingGreaterThan(
    int? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'productivityRating',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      productivityRatingLessThan(
    int? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'productivityRating',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      productivityRatingBetween(
    int? lower,
    int? upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'productivityRating',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduleCountEqualTo(int value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'rescheduleCount',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduleCountGreaterThan(
    int value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'rescheduleCount',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduleCountLessThan(
    int value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'rescheduleCount',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduleCountBetween(
    int lower,
    int upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'rescheduleCount',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduledToIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNull(
        property: r'rescheduledTo',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduledToIsNotNull() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(const FilterCondition.isNotNull(
        property: r'rescheduledTo',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduledToEqualTo(DateTime? value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'rescheduledTo',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduledToGreaterThan(
    DateTime? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'rescheduledTo',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduledToLessThan(
    DateTime? value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'rescheduledTo',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      rescheduledToBetween(
    DateTime? lower,
    DateTime? upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'rescheduledTo',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      scheduledDateEqualTo(DateTime value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'scheduledDate',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      scheduledDateGreaterThan(
    DateTime value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'scheduledDate',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      scheduledDateLessThan(
    DateTime value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'scheduledDate',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      scheduledDateBetween(
    DateTime lower,
    DateTime upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'scheduledDate',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      scheduledStartTimeEqualTo(DateTime value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'scheduledStartTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      scheduledStartTimeGreaterThan(
    DateTime value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'scheduledStartTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      scheduledStartTimeLessThan(
    DateTime value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'scheduledStartTime',
        value: value,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      scheduledStartTimeBetween(
    DateTime lower,
    DateTime upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'scheduledStartTime',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodEqualTo(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'schedulingMethod',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodGreaterThan(
    String value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'schedulingMethod',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodLessThan(
    String value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'schedulingMethod',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodBetween(
    String lower,
    String upper, {
    bool includeLower = true,
    bool includeUpper = true,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'schedulingMethod',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodStartsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.startsWith(
        property: r'schedulingMethod',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodEndsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.endsWith(
        property: r'schedulingMethod',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodContains(String value, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.contains(
        property: r'schedulingMethod',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodMatches(String pattern, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.matches(
        property: r'schedulingMethod',
        wildcard: pattern,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodIsEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'schedulingMethod',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      schedulingMethodIsNotEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        property: r'schedulingMethod',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleEqualTo(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'title',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleGreaterThan(
    String value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'title',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleLessThan(
    String value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'title',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleBetween(
    String lower,
    String upper, {
    bool includeLower = true,
    bool includeUpper = true,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'title',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleStartsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.startsWith(
        property: r'title',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleEndsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.endsWith(
        property: r'title',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleContains(String value, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.contains(
        property: r'title',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleMatches(String pattern, {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.matches(
        property: r'title',
        wildcard: pattern,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleIsEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'title',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      titleIsNotEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        property: r'title',
        value: '',
      ));
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterFilterCondition>
      wasRescheduledEqualTo(bool value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'wasRescheduled',
        value: value,
      ));
    });
  }
}

extension ScheduledTaskQueryObject
    on QueryBuilder<ScheduledTask, ScheduledTask, QFilterCondition> {}

extension ScheduledTaskQueryLinks
    on QueryBuilder<ScheduledTask, ScheduledTask, QFilterCondition> {}

extension ScheduledTaskQuerySortBy
    on QueryBuilder<ScheduledTask, ScheduledTask, QSortBy> {
  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByActualDuration() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'actualDuration', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByActualDurationDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'actualDuration', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByActualStartTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'actualStartTime', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByActualStartTimeDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'actualStartTime', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByColorHex() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'colorHex', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByColorHexDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'colorHex', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByCompletedAt() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'completedAt', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByCompletedAtDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'completedAt', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByCompletionNotes() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'completionNotes', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByCompletionNotesDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'completionNotes', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByCreatedAt() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'createdAt', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByCreatedAtDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'createdAt', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByDuration() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'duration', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByDurationDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'duration', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByGoalId() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'goalId', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByGoalIdDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'goalId', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByIconName() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'iconName', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByIconNameDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'iconName', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByIsAutoGenerated() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'isAutoGenerated', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByIsAutoGeneratedDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'isAutoGenerated', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByIsCompleted() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'isCompleted', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByIsCompletedDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'isCompleted', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByMilestoneCompleted() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'milestoneCompleted', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByMilestoneCompletedDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'milestoneCompleted', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByMilestoneId() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'milestoneId', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByMilestoneIdDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'milestoneId', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByMlConfidence() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'mlConfidence', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByMlConfidenceDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'mlConfidence', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByOriginalScheduledTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'originalScheduledTime', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByOriginalScheduledTimeDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'originalScheduledTime', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByProductivityRating() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'productivityRating', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByProductivityRatingDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'productivityRating', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByRescheduleCount() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'rescheduleCount', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByRescheduleCountDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'rescheduleCount', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByRescheduledTo() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'rescheduledTo', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByRescheduledToDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'rescheduledTo', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByScheduledDate() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'scheduledDate', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByScheduledDateDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'scheduledDate', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByScheduledStartTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'scheduledStartTime', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByScheduledStartTimeDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'scheduledStartTime', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortBySchedulingMethod() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'schedulingMethod', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortBySchedulingMethodDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'schedulingMethod', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByTitle() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'title', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> sortByTitleDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'title', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByWasRescheduled() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'wasRescheduled', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      sortByWasRescheduledDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'wasRescheduled', Sort.desc);
    });
  }
}

extension ScheduledTaskQuerySortThenBy
    on QueryBuilder<ScheduledTask, ScheduledTask, QSortThenBy> {
  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByActualDuration() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'actualDuration', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByActualDurationDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'actualDuration', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByActualStartTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'actualStartTime', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByActualStartTimeDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'actualStartTime', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByColorHex() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'colorHex', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByColorHexDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'colorHex', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByCompletedAt() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'completedAt', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByCompletedAtDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'completedAt', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByCompletionNotes() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'completionNotes', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByCompletionNotesDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'completionNotes', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByCreatedAt() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'createdAt', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByCreatedAtDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'createdAt', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByDuration() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'duration', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByDurationDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'duration', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByGoalId() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'goalId', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByGoalIdDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'goalId', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByIconName() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'iconName', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByIconNameDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'iconName', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenById() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'id', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByIdDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'id', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByIsAutoGenerated() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'isAutoGenerated', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByIsAutoGeneratedDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'isAutoGenerated', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByIsCompleted() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'isCompleted', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByIsCompletedDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'isCompleted', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByMilestoneCompleted() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'milestoneCompleted', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByMilestoneCompletedDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'milestoneCompleted', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByMilestoneId() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'milestoneId', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByMilestoneIdDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'milestoneId', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByMlConfidence() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'mlConfidence', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByMlConfidenceDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'mlConfidence', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByOriginalScheduledTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'originalScheduledTime', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByOriginalScheduledTimeDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'originalScheduledTime', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByProductivityRating() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'productivityRating', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByProductivityRatingDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'productivityRating', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByRescheduleCount() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'rescheduleCount', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByRescheduleCountDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'rescheduleCount', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByRescheduledTo() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'rescheduledTo', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByRescheduledToDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'rescheduledTo', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByScheduledDate() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'scheduledDate', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByScheduledDateDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'scheduledDate', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByScheduledStartTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'scheduledStartTime', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByScheduledStartTimeDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'scheduledStartTime', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenBySchedulingMethod() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'schedulingMethod', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenBySchedulingMethodDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'schedulingMethod', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByTitle() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'title', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy> thenByTitleDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'title', Sort.desc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByWasRescheduled() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'wasRescheduled', Sort.asc);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QAfterSortBy>
      thenByWasRescheduledDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'wasRescheduled', Sort.desc);
    });
  }
}

extension ScheduledTaskQueryWhereDistinct
    on QueryBuilder<ScheduledTask, ScheduledTask, QDistinct> {
  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByActualDuration() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'actualDuration');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByActualStartTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'actualStartTime');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct> distinctByColorHex(
      {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'colorHex', caseSensitive: caseSensitive);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByCompletedAt() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'completedAt');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByCompletionNotes({bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'completionNotes',
          caseSensitive: caseSensitive);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct> distinctByCreatedAt() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'createdAt');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct> distinctByDuration() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'duration');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct> distinctByGoalId() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'goalId');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct> distinctByIconName(
      {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'iconName', caseSensitive: caseSensitive);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByIsAutoGenerated() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'isAutoGenerated');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByIsCompleted() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'isCompleted');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByMilestoneCompleted() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'milestoneCompleted');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByMilestoneId() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'milestoneId');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByMlConfidence() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'mlConfidence');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByOriginalScheduledTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'originalScheduledTime');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByProductivityRating() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'productivityRating');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByRescheduleCount() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'rescheduleCount');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByRescheduledTo() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'rescheduledTo');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByScheduledDate() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'scheduledDate');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByScheduledStartTime() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'scheduledStartTime');
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctBySchedulingMethod({bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'schedulingMethod',
          caseSensitive: caseSensitive);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct> distinctByTitle(
      {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'title', caseSensitive: caseSensitive);
    });
  }

  QueryBuilder<ScheduledTask, ScheduledTask, QDistinct>
      distinctByWasRescheduled() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'wasRescheduled');
    });
  }
}

extension ScheduledTaskQueryProperty
    on QueryBuilder<ScheduledTask, ScheduledTask, QQueryProperty> {
  QueryBuilder<ScheduledTask, int, QQueryOperations> idProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'id');
    });
  }

  QueryBuilder<ScheduledTask, int?, QQueryOperations> actualDurationProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'actualDuration');
    });
  }

  QueryBuilder<ScheduledTask, DateTime?, QQueryOperations>
      actualStartTimeProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'actualStartTime');
    });
  }

  QueryBuilder<ScheduledTask, String?, QQueryOperations> colorHexProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'colorHex');
    });
  }

  QueryBuilder<ScheduledTask, DateTime?, QQueryOperations>
      completedAtProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'completedAt');
    });
  }

  QueryBuilder<ScheduledTask, String?, QQueryOperations>
      completionNotesProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'completionNotes');
    });
  }

  QueryBuilder<ScheduledTask, DateTime, QQueryOperations> createdAtProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'createdAt');
    });
  }

  QueryBuilder<ScheduledTask, int, QQueryOperations> durationProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'duration');
    });
  }

  QueryBuilder<ScheduledTask, int, QQueryOperations> goalIdProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'goalId');
    });
  }

  QueryBuilder<ScheduledTask, String?, QQueryOperations> iconNameProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'iconName');
    });
  }

  QueryBuilder<ScheduledTask, bool, QQueryOperations>
      isAutoGeneratedProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'isAutoGenerated');
    });
  }

  QueryBuilder<ScheduledTask, bool, QQueryOperations> isCompletedProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'isCompleted');
    });
  }

  QueryBuilder<ScheduledTask, bool?, QQueryOperations>
      milestoneCompletedProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'milestoneCompleted');
    });
  }

  QueryBuilder<ScheduledTask, int?, QQueryOperations> milestoneIdProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'milestoneId');
    });
  }

  QueryBuilder<ScheduledTask, double?, QQueryOperations>
      mlConfidenceProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'mlConfidence');
    });
  }

  QueryBuilder<ScheduledTask, DateTime, QQueryOperations>
      originalScheduledTimeProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'originalScheduledTime');
    });
  }

  QueryBuilder<ScheduledTask, int?, QQueryOperations>
      productivityRatingProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'productivityRating');
    });
  }

  QueryBuilder<ScheduledTask, int, QQueryOperations> rescheduleCountProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'rescheduleCount');
    });
  }

  QueryBuilder<ScheduledTask, DateTime?, QQueryOperations>
      rescheduledToProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'rescheduledTo');
    });
  }

  QueryBuilder<ScheduledTask, DateTime, QQueryOperations>
      scheduledDateProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'scheduledDate');
    });
  }

  QueryBuilder<ScheduledTask, DateTime, QQueryOperations>
      scheduledStartTimeProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'scheduledStartTime');
    });
  }

  QueryBuilder<ScheduledTask, String, QQueryOperations>
      schedulingMethodProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'schedulingMethod');
    });
  }

  QueryBuilder<ScheduledTask, String, QQueryOperations> titleProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'title');
    });
  }

  QueryBuilder<ScheduledTask, bool, QQueryOperations> wasRescheduledProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'wasRescheduled');
    });
  }
}
